---
title: "AIS"
author: "Marina Bozinovic"
date: "2023-04-11"
output: html_document
---

#Introduction
AIS download from Marine Cadastre and match to buoy datasets.


Required Packages
```{r, }
library(PAMscapes)
library(tidyverse)
```

-----------------------
From Taiki's AIS Workflow

```{r}
#marcadFiles07 <- downloadMarCadAIS(tracks_SS_07, outDir = "D:/AIS", overwrite = FALSE, unzip = TRUE)
#marcadFiles08 <- downloadMarCadAIS(tracks_SS_08, outDir = "D:/AIS", overwrite = FALSE, unzip = TRUE)
#marcadFiles10 <- downloadMarCadAIS(tracks_SS_10, outDir = "D:/AIS", overwrite = FALSE, unzip = TRUE)
#marcadFiles12 <- downloadMarCadAIS(tracks_SS_12, outDir = "D:/AIS", overwrite = FALSE, unzip = TRUE)
#marcadFiles13 <- downloadMarCadAIS(tracks_SS_13, outDir = "D:/AIS", overwrite = FALSE, unzip = TRUE)
#marcadFiles14 <- downloadMarCadAIS(tracks_SS_14, outDir = "D:/AIS", overwrite = FALSE, unzip = TRUE)
#marcadFiles16 <- downloadMarCadAIS(tracks_SS_16, outDir = "D:/AIS", overwrite = FALSE, unzip = TRUE)
#marcadFiles18 <- downloadMarCadAIS(tracks_SS_18, outDir = "D:/AIS", overwrite = FALSE, unzip = TRUE)
#marcadFiles19 <- downloadMarCadAIS(tracks_SS_19, outDir = "D:/AIS", overwrite = FALSE, unzip = TRUE)
#marcadFiles20 <- downloadMarCadAIS(tracks_SS_20, outDir = "D:/AIS", overwrite = FALSE, unzip = TRUE)
#marcadFiles21 <- downloadMarCadAIS(tracks_SS_21, outDir = "D:/AIS", overwrite = FALSE, unzip = TRUE)
#marcadFiles22 <- downloadMarCadAIS(tracks_SS_22, outDir = "D:/AIS", overwrite = FALSE, unzip = TRUE)
#marcadFiles23 <- downloadMarCadAIS(tracks_SS_23, outDir = "D:/AIS", overwrite = FALSE, unzip = TRUE)
```

Subset to US West Coast
```{r}
subsetMarCadAIS(inDir="D:/AIS", outDir="D:/AIS/AIS_West", name='West_', 
                latRange=c(20,50), lonRange=c(-140,-110),
                overwrite=FALSE, progress=TRUE)
```
Now read into R only ais points that come in contact with buoys
```{r}
ais_near_07 <- readLocalAIS(tracks_SS_07, aisDir="D:/AIS/AIS_West", distance=10e3) %>%
   filter(vesselLength >= 100)  #remove vessels under 100m in length

ais_near_08 <- readLocalAIS(tracks_SS_08, aisDir="D:/AIS/AIS_West", distance=10e3) %>%
   filter(vesselLength >= 100)  #remove vessels under 100m in length

ais_near_10 <- readLocalAIS(tracks_SS_10, aisDir="D:/AIS/AIS_West", distance=10e3) %>%
   filter(vesselLength >= 100)  #remove vessels under 100m in length

ais_near_12 <- readLocalAIS(tracks_SS_12, aisDir="D:/AIS/AIS_West", distance=10e3) %>%
   filter(vesselLength >= 100)  #remove vessels under 100m in length

ais_near_13 <- readLocalAIS(tracks_SS_13, aisDir="D:/AIS/AIS_West", distance=10e3) %>%
   filter(vesselLength >= 100)  #remove vessels under 100m in length

ais_near_14 <- readLocalAIS(tracks_SS_14, aisDir="D:/AIS/AIS_West", distance=10e3) %>%
   filter(vesselLength >= 100)  #remove vessels under 100m in length

ais_near_16 <- readLocalAIS(tracks_SS_16, aisDir="D:/AIS/AIS_West", distance=10e3) %>%
   filter(vesselLength >= 100)  #remove vessels under 100m in length

ais_near_18 <- readLocalAIS(tracks_SS_18, aisDir="D:/AIS/AIS_West", distance=10e3) %>%
   filter(vesselLength >= 100)  #remove vessels under 100m in length

ais_near_19 <- readLocalAIS(tracks_SS_19, aisDir="D:/AIS/AIS_West", distance=10e3) %>%
   filter(vesselLength >= 100)  #remove vessels under 100m in length

ais_near_20 <- readLocalAIS(tracks_SS_20, aisDir="D:/AIS/AIS_West", distance=10e3) %>%
   filter(vesselLength >= 100)  #remove vessels under 100m in length

ais_near_21 <- readLocalAIS(tracks_SS_21, aisDir="D:/AIS/AIS_West", distance=10e3) %>%
   filter(vesselLength >= 100)  #remove vessels under 100m in length
#empty table because no large vessels interacted with this buoy

ais_near_22 <- readLocalAIS(tracks_SS_22, aisDir="D:/AIS/AIS_West", distance=10e3) %>%
   filter(vesselLength >= 100)  #remove vessels under 100m in length

ais_near_23 <- readLocalAIS(tracks_SS_23, aisDir="D:/AIS/AIS_West", distance=10e3) %>%
   filter(vesselLength >= 100)  #remove vessels under 100m in length
```

Match AIS points with buoy points
```{r}
gpsClose07 <- addAIS(tracks_SS_07, ais_near_07, interpType = 'close', interpTime = 120)
gpsClose08 <- addAIS(tracks_SS_08, ais_near_08, interpType = 'close', interpTime = 120)
gpsClose10 <- addAIS(tracks_SS_10, ais_near_10, interpType = 'close', interpTime = 120)
gpsClose12 <- addAIS(tracks_SS_12, ais_near_12, interpType = 'close', interpTime = 120)
gpsClose13 <- addAIS(tracks_SS_13, ais_near_13, interpType = 'close', interpTime = 120)
gpsClose14 <- addAIS(tracks_SS_14, ais_near_14, interpType = 'close', interpTime = 120)
gpsClose16 <- addAIS(tracks_SS_16, ais_near_16, interpType = 'close', interpTime = 120)
gpsClose18 <- addAIS(tracks_SS_18, ais_near_18, interpType = 'close', interpTime = 120)
gpsClose19 <- addAIS(tracks_SS_19, ais_near_19, interpType = 'close', interpTime = 120)
gpsClose20 <- addAIS(tracks_SS_20, ais_near_20, interpType = 'close', interpTime = 120)
gpsClose21 <- addAIS(tracks_SS_21, ais_near_21, interpType = 'close', interpTime = 120) #empty table
gpsClose22 <- addAIS(tracks_SS_22, ais_near_22, interpType = 'close', interpTime = 120)
gpsClose23 <- addAIS(tracks_SS_23, ais_near_23, interpType = 'close', interpTime = 120)
```

Create column 'shipsin10km' that displays number of ships associated with timestamp
Need to make a loop!
```{r}
# Viewing only ships within 10 km of buoys.
close2ships7 <- gpsClose07 %>% filter(shipDist < 10e3)

#Add column of ROUNDED UTC values to the lowest minute. Allows common field to bind
z <- as.POSIXct(close2ships7$UTC)
close2ships7$UTCrnd <- lubridate::floor_date(z, "minute")

#Bind rows with ship nearby
#Summarize unique ships and display number of nearby vessels
nearbyShp07 <- inner_join(tracks_ss_07, close2ships7, by = join_by("UTC" == "UTCrnd")) %>%
  select(UTC, UTC2, MMSI, vesselLength, vesselType, shipLat, shipLong, shipDist) %>%
  group_by(UTC2) %>%
  summarize(shipin10km = n_distinct(MMSI))
    
# ready to join to main df and add zeros to Null values
```


