---
title: "06_gam"
author: "Marina Bozinovic"
date: "2023-10-09"
output: html_document
---

Compare results of GAM to Virgili et al. 2019, Fiedler et al. 2023



Required Packages
```{r setup}
library(tidyverse)
library(mgcv)
```

Load allDrifts object
```{r setup, include=FALSE}
load(allDrifts, file = "data/allDrifts.rda")
```


### GAMs

```{r}
model3 <- gam(Wpresence ~ depth + TOL_125 + dist2shore + mldTemp, 
              data = allDrifts, family = binomial)
#plot(model3)

#try fitting linear model

lm_depth <- lm(Wpresence ~ depth, data = GPSwhaleAISenvSS10)
ggplot(allDrifts, aes(sst_mean, chlorophyll_mean)) +
  geom_point() +
  geom_smooth()
```
Categorical term
```{r}
# ALL variables, GAM
model1 <- gam(Wpresence>0 ~ s(TOL_125) + s(TOL_2000) + s(depth) + s(mldDepth) + s(Latitude)
              + s(Longitude) + s(sst_mean) + s(curl_mean) + s(dist2slope) 
              + s(bathy_slope) + s(dist2shore) + s(chlorophyll_mean) + s(ssh_mean) 
              + s(mldTemp) + s(ttDepth) + s(ttTemp) + s(temp400) + s(sal400),
              data = allDrifts, family = binomial, method = "REML")

# ALL variables, GLM
model1GLM <- glm(Wpresence ~ TOL_125 + TOL_2000 + depth + mldDepth + Latitude
              + Longitude + sst_mean + curl_mean + dist2slope
              + bathy_slope + dist2shore + chlorophyll_mean + ssh_mean 
              + mldTemp + ttDepth + ttTemp + temp400 + sal400,
              data = allDrifts, family = binomial)

# By species? doesnt work, may need to create dummy variables
model2 <- gam(Wpresence ~ s(sst_mean, by = as.factor(species)), 
              data = allDrifts, family = binomial, method = "REML")

# Soundscape metrics only, GAM
model4 <- gam(Wpresence ~ s(TOL_125, k = 10) + 
                s(TOL_2000, k = 10),
              data = allDrifts, family = binomial, method = "REML")

# Soundscape metrics only, GLM
model4GLM <- glm(Wpresence ~ TOL_125 + TOL_2000,
              data = allDrifts, family = binomial)

model125 <- gam(Wpresence ~ s(TOL_125, k = 10),
              data = allDrifts, family = binomial, method = "REML")
plot(model125, trans = plogis)
summary(model125)
gam.check(model125)

# Environmental var only
model5 <- gam(Wpresence ~ s(depth) + s(mldDepth) + s(Latitude)
              + s(Longitude) + s(sst_mean) + s(curl_mean) + s(dist2slope) 
              + s(bathy_slope) + s(dist2shore) + s(chlorophyll_mean) + s(ssh_mean) 
              + s(mldTemp) + s(ttDepth) + s(ttTemp) + s(temp400) + s(sal400),
              data = allDrifts, family = binomial, method = "REML")

plogis(coef(model1[1]))
summary(model1)
summary(model4)
summary(model5)
summary(model4GLM)
plot(model4GLM)
gam.check(model1)
gam.check(model4)

#Log odds scale (when used with family = binomial)
plot(model1, pages = 6)
plot(model4, pages = 4, trans = plogis)

#Probability scale + centered on the intercept + adding intercept-related uncertainty with seWithMean arg
plot(model1, pages = 14, trans = plogis,
     shift = coef(model1)[1])#,
     #seWithMean = TRUE)

plot(model2, pages = 1, trans = plogis,
     shift = coef(model2)[1])

plot(model4, pages = 6, trans = plogis,
     shift = coef(model4)[1])
```

Top 5 environmental variables (by RF) with one drift
```{r}
# Environ only
model1 <- gam(Wpresence>0 ~ depth + sst_mean + curl_mean + ttDepth + sal400,
              data = GPSwhaleAISenvSS23, family = binomial, method = "REML")

plot(model1, trans = plogis, all.terms = TRUE)
k.check(model1)
summary(model1)
gam.check(model1)


# Add soundscape metrics to model 1
model2 <- gam(Wpresence>0 ~ depth + sst_mean + curl_mean + ttDepth + sal400
              + TOL_125 + TOL_2000,
              data = GPSwhaleAISenvSS10, family = binomial, method = "REML")


#plot(model2, trans = plogis) ## doesn't work
summary(model2)
gam.check(model2)
# 18.3% deviance explained (buoy 7)
# 1.25% deviance explained (buoy 8)
# 8.56% deviance explained (buoy 10)
# 1.39% deviance explained (buoy 12)
# 11.1% deviance explained (buoy 13)
# 28% deviance explained (buoy 14)
# 15% deviance explained (buoy 16)
# 9.92% deviance explained (buoy 18)
# 8.57% deviance explained (buoy 19)
# 7.3% deviance explained (buoy 20)
# 38.3% deviance explained (buoy 21)
# 15.2 % deviance explained (buoy 22)
# 20.4% deviance explained (buoy 23)

# Depth parameter only
model_depth_only <- gam(Wpresence>0 ~ depth,
                        data = GPSwhaleAISenvSS10, family = binomial, method = "REML")
summary(model_depth_only)
gam.check(model_depth_only)
```
GAM with FULL DATASET (not great)
```{r}
alldriftGAM <- gam(Wpresence>0 ~ depth + sst_mean + mldTemp + ttDepth + sal400
              + TOL_125 + TOL_2000,
              data = allDrifts, family = binomial, method = "REML")
summary(alldriftGAM)
gam.check(alldriftGAM)
```


GAMs with s()
```{r}
# Environ only, with s()
model3 <- gam(Wpresence>0 ~ s(depth) + s(sst_mean) + s(curl_mean) + 
                s(ttDepth) + s(sal400),
              data = GPSwhaleAISenvSS07, family = binomial, method = "REML")

plot(model3, trans = plogis)
summary(model3)
gam.check(model3)
# 61.9 % deviance explained (buoy 7)
# 1.42% deviance explained (buoy 8)
# 12.5% deviance explained (buoy 10)
# 1.66% deviance explained (buoy 12)
# 12.8% deviance explained (buoy 13)
# 41.4% deviance explained (buoy 14)
# 39% deviance explained (buoy 16)
# 16.6% deviance explained (buoy 18)
# 15.5% deviance explained (buoy 19)
# 5.8% deviance explained (buoy 20)
## Iteration limit reached without full convergence -- 71.7% deviance explained (buoy 21) ???
# 18.6% deviance explained (buoy 22)
# 49.6% deviance explained (buoy 23)

#Add soundscape metrics to model 3
model4 <- gam(Wpresence>0 ~ s(depth) + s(sst_mean) + s(curl_mean) + 
                s(ttDepth) + s(sal400) + s(TOL_125) + s(TOL_2000),
              data = GPSwhaleAISenvSS07, family = binomial, method = "REML")

plot(model4, trans = plogis)
summary(model4)
gam.check(model4)
# 14.5% deviance explained

# mix and match?
model5 <- gam(BWpresence>0 ~ depth + sst_mean + s(mldTemp) + 
                s(ttDepth) + sal400,
              data = fulltrack21, family = binomial, method = "REML")

summary(model5)
gam.check(model5)
# 57.4 % deviance explained
plot(model5)


```
Higher edfs describe more wiggly curves. Doesn't mean significant

#GAM by ZC
```{r}
ZC_filt <- allDrifts %>% 
  filter(species %in% c("ZC", NA))

ZC_GAM <- gam(Wpresence>0 ~ depth + mldTemp + ttDepth + sal400,
              data = ZC_filt, family = binomial, method = "REML")
summary(ZC_GAM)
gam.check(ZC_GAM)
```

# GAM by PM
```{r}
PM_filt <- allDrifts %>% 
  filter(species %in% c("PM", NA))

PM_GAM <- gam(Wpresence>0 ~ depth + sst_mean + mldTemp + ttDepth + sal400 +
                TOL_125 + TOL_2000,
              data = PM_filt, family = binomial, method = "REML")
summary(PM_GAM)
gam.check(PM_GAM)

# Using variables from Fiedler et al. 2023 for sperm whales
PM_GAM_fiedlerVar <- gam(Wpresence>0 ~ depth + mldDepth + curl_mean + ssh_mean + sal400,
              data = PM_filt, family = binomial, method = "REML")
summary(PM_GAM_fiedlerVar)
```


