---
title: "Thesis outline"
author: Marina Bozinovic
format: docx
editor: visual
---

## Goal 1: Characterize the soundscape/acoustic habitat

#### Explore the relationship (spatial/temporal variation?) between soundscape metrics and environmental variables, and beaked whale (BW) detections. (Alternative: Describe the acoustic environment where deep-diving species are present/absent.)

-   Exploratory: Create histograms, scatterplots, time series, facet graphs of:
    -   A soundscape metric/BW presence + absence/env variable
        -   Comparing TOL intensities between drift 8 and 10 (**only two drifts for now**)
        -   Broadband levels, Third-octave levels at 63, 125, 2000, 5000, 20000 Hz
            -   Are we interested in high frequencies (20 kHz)?
        -   Which frequencies had the most loudness? What does the soundscape look like when there are high BW detections?
    -   Oceanographic characteristics
        -   Bottom depth (**done for drift 8**)

        -   Bottom slope (**done for drift 8**)

        -   Distance from shore **(done for drift 8)**

        -   Distance from continental shelf (**done for drift 8**)

        -   Sea surface temperature **(done for drift 8**)

        -   Sea surface height anomalies **(done for drift 8)**

        -   Sea surface height slope (in progress)

        -   Curl of wind stress (in progress)

        -   Mixed layer depth (MLD) **(done for drift 8**)

        -   Mixed layer depth Temperature **(done for drift 8**)

        -   Thermocline temperature (TTemp) **(done for drift 8**)

        -   Thermocline depth **(done for drift 8**)

        -   Temperature at 400 m **(done for drift 8**)

        -   Salinity at 400 m **(done for drift 8**)

        -   Chlorophyll-a **(done for drift 8**)
    -   Other potential variables: seasonality, hour of the day (create time series for avg daily env.variable)
    -   Questions: Does soundscape change when conditions change? Is sound seasonal?
-   Fit a model (GAM, possibly zero-inflated, GLM, random forest, AIC)

## Goal 2: Influence from vessels (connect sound to a source)

#### Explore how vessel presence influences and contributes to the soundscape

-   Find instances of vessel in vicinity of drift vs. drift alone and compare

    -   Number of ship passages, types of ships (**IN PROGRESS**)

        -   Create buffer around whale detections (using 50nmi)

        -   Find AIS vessels by lat/long that lie within buffer

        -   Identify number of vessels that pass each drift

    -   Closest ship passage (When a ship has a close encounter with a drift, how close is it on average? How is soundscape affected?)

-   Does vessel presence create a louder soundscape?

    -   Compare TOL 63 and125 intensities vs. ship presence

-   Chronic vs. acute sound events

    -   Instances where drifts and vessels overlap, plot time on x-axis and TOL125 on y axis
